name: meld_classifier_parallel
channels:
  - defaults
  - pog87
  - conda-forge
dependencies:
  - python
  - tensorflow
  - pytest
  - nibabel
  - pillow
  - jupyterlab
  - ptitprince
  - scikit-image
  - h5py
  - fpdf
  - pip
  - pip:
    - matplotlib_surface_plotting
    - potpourri3d
#    - umap-learn
    - nilearn
    - neuroCombat
    - alibi
    - patsy
    - matplotlib
