name: meld_classifier
channels:
  - defaults
  - pog87
  - conda-forge
dependencies:
  - python=3.7
  - tensorflow
  - pytest
  - nibabel
  - pillow
  - jupyterlab
  - ptitprince
  - h5py
  - scikit-learn
  - pip
  - pip:
    - matplotlib_surface_plotting
    - potpourri3d
#    - umap-learn
    - nilearn
    - git+https://github.com/kwagstyl/neuroCombat.git@estimates_shrink
    - alibi
